### ISSUE TITLE
【漏洞】导入了未依赖的包

### ISSUE THREAD

**Issue by NKID00** [Nemo2011/bilibili_api#13]
**Python 版本：** 3.10.4

**模块版本：** 10.0.1

**运行环境：** Kubuntu 22.04 LTS

**模块路径：** bilibili_api.user

**报错信息：**

```
Traceback (most recent call last):
  File "<unrelated>.py", line 8, in <module>
    from bilibili_api.user import User, BangumiType
  File "<unrelated>/.venv/lib/python3.10/site-packages/bilibili_api/user.py", line 11, in <module>
    from pytest import param
ModuleNotFoundError: No module named 'pytest'
```

---

https://github.com/Nemo2011/bilibili_api/blob/9d02c3fa881ea307db99d25b2c7cfe989f063d95/bilibili_api/user.py#L11

`requirements.txt` 中没有依赖 pytest 但仍导入导致报错。（而且导入之后并未使用）

**Comment by Nemo2011** [comment]
已解决，请安装最新版本 10.1.0.a1
`pip install bilibili-api-python==10.1.0a1`
