### ISSUE TITLE
【建议】要不在原仓库给你引个流？

### ISSUE THREAD

**Issue by MoyuScript** [Nemo2011/bilibili_api#9]
没想到还真有人接手做了，看了一圈貌似还可以。原仓库主要是我实在是没精力去维护了，要不在原仓库给你引个流？[狗头]

不介意的话也可以把原仓库转给你，我偶尔冒泡帮个忙。

**Comment by Nemo2011** [comment]
谢谢引流，这样正好可以推广一下仓库。以后我会继续努力把仓库维护下去的。💪
完了害羞了（误

**Comment by MoyuScript** [comment]
> 谢谢引流，这样正好可以推广一下仓库。以后我会继续努力把仓库维护下去的。💪 完了害羞了（误

已经在 Readme 标上了
